# Generated by Django 6.0.4 on 2026-05-04 03:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Team Name')),
                ('team_type', models.CharField(blank=True, max_length=200)),
                ('jira_project_name', models.CharField(blank=True, max_length=200)),
                ('development_focus', models.TextField(blank=True)),
                ('key_skills', models.TextField(blank=True)),
                ('agile_practices', models.CharField(blank=True, max_length=200)),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('DISBANDED', 'Disbanded'), ('MERGED', 'Merged'), ('REFORMED', 'Reformed')], default='ACTIVE', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, related_name='teams', to='organization.department')),
                ('team_leader', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='led_teams', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='ContactChannel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel_type', models.CharField(choices=[('SLACK', 'Slack'), ('JIRA', 'Jira'), ('STANDUP', 'Daily Standup'), ('WIKI', 'Wiki'), ('EMAIL', 'Email')], max_length=10)),
                ('channel_name', models.CharField(max_length=200)),
                ('value', models.CharField(max_length=500)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='contact_channels', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='CodeRepo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('repo_name', models.CharField(max_length=200)),
                ('repo_url', models.URLField(max_length=2048)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='repos', to='teams.team')),
            ],
        ),
        migrations.CreateModel(
            name='TeamDependency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dependency_type', models.CharField(blank=True, choices=[('Infrastructure Support', 'Infrastrucure Support'), ('Bug Resolution', 'Bug Resolution'), ('CI/CD Support', 'CI/CD Support'), ('Security Fixes', 'Security Fixes'), ('Agile Coaching', 'Agile Coaching'), ('Other', 'Other')], max_length=50)),
                ('depends_on_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependents', to='teams.team')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dependencies', to='teams.team')),
            ],
            options={
                'unique_together': {('team', 'depends_on_team')},
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role_in_team', models.CharField(blank=True, max_length=120)),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='teams.team')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_memberships', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('team', 'user')},
            },
        ),
    ]
